services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    App\Command\:
        resource: '../../src/Command'

    Shopsys\FrameworkBundle\Command\RedisCleanCacheOldCommand: ~