language: bash

env:
    global:
        - TRAVIS_USER_ID=$(id -u)
        - TRAVIS_GROUP_ID=$(id -g)

before_install:
    - cp -f ./docker/conf/docker-compose.yml.dist ./docker-compose.yml
    - "sed -i 's#www_data_uid: 1000#www_data_uid: 2000#' ./docker-compose.yml"
    - "sed -i 's#www_data_gid: 1000#www_data_uid: 2000#' ./docker-compose.yml"
    - cat ./docker-compose.yml
    - echo $TRAVIS_USER_ID
    - echo $TRAVIS_GROUP_ID

install:
    - docker-compose up -d postgres elasticsearch redis selenium-server php-fpm webserver
    - docker-compose exec php-fpm composer install --no-interaction

script:
    - docker-compose exec php-fpm ./phing db-create test-db-create build-demo-dev tests-acceptance
