apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: shopsys
    annotations:
        kubernetes.io/ingress.class: nginx
        ingress.kubernetes.io/ssl-redirect: "true"
spec:
    tls:
        -   hosts:
                - "{{FIRST_DOMAIN_HOSTNAME}}"
                - "{{SECOND_DOMAIN_HOSTNAME}}"
                - "{{THIRD_DOMAIN_HOSTNAME}}"
            secretName: domain-ssl-certificates
