snc_redis:
    clients:
        bestselling_products:
            type: 'phpredis'
            alias: 'bestselling_products'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:cache:bestselling_products:'
        doctrine_metadata:
            type: 'phpredis'
            alias: 'doctrine_metadata'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:cache:doctrine_metadata:'
        doctrine_query:
            type: 'phpredis'
            alias: 'doctrine_query'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:cache:doctrine_query:'
        global:
            type: 'phpredis'
            alias: 'global'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%'
        twig:
            type: 'phpredis'
            alias: 'twig'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%%build-version%:twig:'
        session:
            type: 'phpredis'
            alias: 'session'
            dsn: 'redis://%redis_host%'
            options:
                prefix: '%env(REDIS_PREFIX)%session:'
    session:
        client: 'session'
